export const translations = {
  en: {
    employees: 'Employees',
    addEmployee: 'Add Employee',
    editEmployee: 'Edit Employee',
    search: 'Search...',
    cancel: 'Cancel',
    approve: 'Approve',
    listView: 'List View',
    cardView: 'Card View',
    firstName: 'First Name',
    lastName: 'Last Name',
    birthDate: 'Date of Birth',
    employmentDate: 'Date of Employment',
    phone: 'Phone',
    email: 'Email',
    department: 'Department',
    position: 'Position',
    select: 'Select',
    save: 'Save',
    cancel: 'Cancel',
    youAreEditing: 'You are editing ',
    employeeAdded: 'Employee added successfully!',
    error: 'Error: ',
    employeeNotFound: 'Employee not found',
    employeeUpdated: 'Employee updated successfully!',

    search: 'Search',
    employeeList: 'Employee List',
    confirmdel1: 'Selected Employee record of ',
    confirmdel2: ' will be deleted.',
    confirmEdit: 'Do you want to edit the record of :',
    confirmEdit2: 'Do you want to save the changes?',
    confirmAdd: 'Do you want to add :',
    areYouSure: 'Are you sure?',
    proceed: 'Proceed',
    actions: 'Actions',
    loading: 'Loading employees',
    noEmployee: 'No employees found',
    employeeDeleted: 'Employee was deleted successfully!',
    delete: 'Delete',
    edit: 'Edit',
    emailExists: 'This mail adress is already in use!',
    phoneExists: 'This phone number is already in use!',
  },
  tr: {
    employees: 'Çalışanlar',
    addEmployee: 'Çalışan Ekle',
    editEmployee: 'Çalışanı Düzenle',
    search: 'Ara...',
    cancel: 'İptal',
    approve: 'Onayla',
    listView: 'Liste Görünümü',
    cardView: 'Kart Görünümü',
    firstName: 'İsim',
    lastName: 'Soyisim',
    birthDate: 'Doğum Tarihi',
    employmentDate: 'İşe Giriş Tarihi',
    phone: 'Telefon',
    email: 'E-posta',
    department: 'Departman',
    position: 'Pozisyon',
    select: 'Seçiniz',
    save: 'Kaydet',
    cancel: 'İptal',
    youAreEditing: 'Şu kişiyi düzenliyorsunuz: ',
    employeeAdded: 'Çalışan başarıyla eklendi!',
    error: 'Hata: ',
    employeeNotFound: 'Çalışan bulunamadı',
    employeeUpdated: ' Çalışan başarıyla güncellendi!',
    search: 'Ara',
    employeeList: 'Çalışan Listesi',
    confirmdel1: 'Seçilen ',
    confirmdel2: ', kişisinin kaydı silinecektir.',
    confirmEdit: 'Kişinin kaydını düzenlenmek istiyor musunuz :',
    confirmEdit2: 'Değişiklikleri kaydetmek istiyor musunuz?',
    confirmAdd: 'Şu kişiyi eklemek istiyor musunuz :',
    areYouSure: 'Emin misiniz?',
    proceed: 'Devam Et',
    actions: 'İşlemler',
    loading: 'Çalışanlar yükleniyor',
    noEmployee: 'Çalışan kaydı bulunamadı',
    employeeDeleted: 'Çalışan başarı ile silindi!',
    delete: 'Sil',
    edit: 'Düzenle',
    emailExists: 'Bu email zaten kayıtlı!',
    phoneExists: 'Bu telefon numarası zaten kayıtlı!',
  },
};
